#!/usr/bin/bash -e

DBHOST=127.0.0.1
DBUSER=postgres
export PGPASSWORD=0oBSTinatenEss#maRyl7uMbeL0@3162 # do this in a more secure fashion
DBNAME=postgres
SCHEMA=public
SCRIPT_PATH=$(realpath $0)
HOOKS_PATH=$(dirname $SCRIPT_PATH)
GITREPO=$HOOKS_PATH/../..
DUMP=$GITREPO/dbdumps
NEW=$DUMP/schema.sql
OLD=$NEW.old

DIR=$(pwd)
cd $GITREPO

mv $NEW $OLD

pg_dump -h $DBHOST -U $DBUSER -n $SCHEMA -Fp -s -f $NEW $DBNAME

# NOTE : ignore .old

if cmp -s $OLD $NEW; then
    echo Same
else
    echo Differ
    exec git add $NEW
    exec git commit $NEW -m "$DBNAME DB update"
    echo "public schema metadata commited"

    exec git push # assuming you have a remote to push to
    echo "schema+data pushed"
fi
cd $DIR
